import asyncio
import os
import sys
from datetime import datetime, timezone
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from app.core.db import connect_to_mongo, close_mongo_connection
from app.repositories.vessel_repository import VesselRepository

async def test():
    await connect_to_mongo()
    v = VesselRepository()
    
    # 1. Print a sample record to see what timezone is stored
    doc = await v.collection.find_one()
    if doc:
        print("Sample record timestamp:", doc.get("timestamp"))
        print("Sample record timestamp type:", type(doc.get("timestamp")))
    else:
        print("DB is empty!")
        return

    # 2. Try the exact query generated by drift engine
    # start = 10:30 - 2.5h = 08:00 UTC
    # end = 10:30 - 1.5h = 09:00 UTC
    start_time = datetime(2025, 1, 1, 8, 0, 0, tzinfo=timezone.utc)
    end_time = datetime(2025, 1, 1, 9, 0, 0, tzinfo=timezone.utc)
    
    query = {
        "timestamp": {"$gte": start_time, "$lte": end_time}
    }
    cursor = v.collection.find(query)
    cands = await cursor.to_list(None)
    print(f"Candidates by time: {len(cands)}")
    for c in cands:
        print(f"  {c['vessel_id']} at {c['location']['coordinates']} at {c['timestamp']}")

    await close_mongo_connection()

if __name__ == "__main__":
    asyncio.run(test())
